In [ ]:
import cv2
import numpy as np

frame=cv2.imread('/Users/kaushikchaturvedula/python/face_recognition/Project_filter/Jamie_Before.jpg')
mustache=cv2.imread('/Users/kaushikchaturvedula/python/face_recognition/Project_filter/mustache.png')
glasses=cv2.imread('/Users/kaushikchaturvedula/python/face_recognition/Project_filter/glasses.png')
face_cascade=cv2.CascadeClassifier('/Users/kaushikchaturvedula/python/face_recognition/Project_filter/haarcascade_frontalface_default.xml')
eyes_cascade=cv2.CascadeClassifier('/Users/kaushikchaturvedula/python/face_recognition/Project_filter/haarcascade_eye_tree_eyeglasses.xml')
nose_cascade=cv2.CascadeClassifier('/Users/kaushikchaturvedula/python/face_recognition/Project_filter/haarcascade_mcs_nose.xml')

while True:
    gray_frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(gray_frame,1.2,4)
    if(len(faces)==0):
        continue
    faces=sorted(faces,key=lambda f:f[2]*f[3])
    for (x,y,w,h) in faces[-1:]:
        roi_gray = gray_frame[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
    eyes = eyes_cascade.detectMultiScale(gray_frame)
    print(eyes)
    for ex,ey,ew,eh in eyes:
        if(ex>40 and ey<300 and ex<250):
            init_x=ex
            init_y=ey
            final_x=init_x+2*ew+25
            final_y=ey+eh
            glasses=cv2.resize(glasses,(final_x-init_x,final_y-init_y),interpolation=True)
            frame[init_y:final_y,init_x:final_x] = cv2.bitwise_and(frame[init_y:final_y,init_x:final_x],glasses,mask=None)
    noses=nose_cascade.detectMultiScale(gray_frame)
    for (ex,ey,ew,eh) in noses:
        init_x=ex-15
        init_y=ey+50
        final_x=ex+ew+15
        final_y=ey+eh+25
        mustache=cv2.resize(mustache,(final_x-init_x,final_y-init_y),interpolation=cv2.INTER_AREA)
        frame[init_y:final_y,init_x:final_x]= cv2.bitwise_and(frame[init_y:final_y,init_x:final_x],mustache , mask=None)
    cv2.imshow("gray_frame",frame)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    break

print("hello")

[[419 374  87  87]
 [249 380  86  86]
 [  6 438  88  88]]
