# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.17.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
vector=np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [5]:
arr=np.zeros([2,2]) #array of 2X2 matrix
print("memory size:",arr.itemsize*arr.size,"bytes")

memory size: 32 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
np.add? #using ? tag we can find the functions full documentation

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
v1=np.zeros(10)
v1[4]=1    #changing the 5th value to 1
print(v1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
v2=np.array(list(range(10,50)))
print(v2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [15]:
v1=np.array([1,2,3,4])
reverse=v1[::-1]   #reversing a vector using slice operator
print(reverse)

[4 3 2 1]


9.Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
matrix=np.arange(0,9).reshape(3,3)  #reshapes to 3X3 matrix -the values from 0 to 8
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
arr=[1,2,0,0,4,0]
indices=list(np.nonzero(arr)) #returns an array of non-zero indices
print(indices)

[array([0, 1, 4])]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
matrix=np.identity(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [30]:
import numpy as np
xmat = np.random.random((3,3,3))  #generates random values in array 3x3x3
print(xmat)

[[[0.7795804  0.80325285 0.57292429]
  [0.0773934  0.97696891 0.29938449]
  [0.48401302 0.60100794 0.80688301]]

 [[0.79614359 0.03584803 0.70592738]
  [0.39697633 0.11120257 0.85775312]
  [0.33735228 0.3890257  0.03579462]]

 [[0.03149942 0.36884117 0.68590491]
  [0.66296768 0.07667473 0.84666471]
  [0.31326014 0.23212441 0.15451844]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [32]:
arr=np.random.random((10,10))  #creates 10x10 array
minimum=arr.min() #to find minimum
maximum=arr.max() #to find maximum
print("Min val:",minimum,"and Max val:",maximum)

Min val: 0.0004826495928764718 and Max val: 0.9968789551749785


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [33]:
v=np.random.random(30) #creating an array of 30 size
mean=np.sum(v)/30       #to find mean
print(mean)

0.5136619797329247


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [37]:
arr=np.ones((4,4))
arr[1:-1,1:-1]=0 #making inside 1s as 0s
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [72]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("bordered array")
x = np.pad(array=x, pad_width=1, constant_values=0) #adding an extra width of 0s around the existing array
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
bordered array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

In [ ]:

0 * np.nan           # nan
np.nan == np.nan     # False
np.inf > np.nan      # False
np.nan - np.nan      # nan
0.3 == 3 * 0.1       # False

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [74]:
arr=np.zeros(shape=(5,5))
arr[1:,:-1]=np.diag([1,2,3,4]) #inserting 1,2,3,4 just below the diagonal
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [53]:
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [79]:
np.unravel_index(100, shape=(6, 7, 8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [84]:
a=np.array([[0,1],[1,0]])
print(np.tile(a,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [69]:
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.88361476 0.61239952 0.70632983]
 [0.7165604  0.46036099 0.49016805]
 [0.1503548  0.54700578 0.67259645]]
After normalization:
[[1.         0.63012402 0.75822363]
 [0.77217581 0.42277801 0.46342807]
 [0.         0.54094183 0.71221897]]


 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [87]:
color = np.dtype([('R', np.ubyte, 1),
                  ('G', np.ubyte, 1),             #ubyte stands for unsigned char
                  ('B', np.ubyte, 1),
                  ('A', np.ubyte, 1)])
color

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [92]:
a=np.random.randint(16,size=(5,3))
b=np.random.randint(7,size=(3,2))
np.dot(a,b)              #MATRIX MULTIPLICATION

array([[ 23,  54],
       [ 74,  93],
       [ 61,  54],
       [ 97,  98],
       [133, 109]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [98]:
x = np.arange(11)
print(x)
x[(x>=3)&(x<=8)]=-x[(x>=3)&(x<=8)]   #boolean value indexing i.e if(x>=3) then change the value and likeways 
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

In [102]:

# Author: Jake VanderPlas
                          
print(sum(range(5),-1))              #answer:
from numpy import *                    # 10
print(sum(range(5),-1))                # 10

10
10


In [ ]:
# answer: 10
      #  10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [103]:
Z = np.arange(3)
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z    # ValueError

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

In [104]:

np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)      #output:  array([-9.22337204e+18])


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

 29. How to round away from zero a float array ? (★☆☆)

In [105]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([-3., -9.,  1.,  2.,  2., -6.,  5., -8.,  5., -7.])

#### 30. How to find common values between two arrays? (★☆☆)

In [106]:
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)    #False


In [ ]:
#False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [109]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2019-12-24
Today:  2019-12-25
Tomorrow:  2019-12-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [111]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
x

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [112]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [113]:
x = np.random.uniform(-10, 10, 10)
x.astype(np.int32)
np.trunc(x)

array([ 9.,  2.,  6.,  4.,  3., -4., -2.,  4., -9., -6.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [114]:
x = np.zeros((5, 5))
x += np.arange(5)     #adding the individual elements and storing in x
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [115]:
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

 39. Create a vector of size 10 with values ranging from 0 to 11, both excluded (★★☆)

In [117]:
np.linspace(start=1, stop=11, num=10, endpoint=False)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [120]:
arr = np.random.random(size=10)
print(arr)
arr.sort()
arr

[0.74388177 0.19516976 0.12989538 0.39765369 0.93482647 0.67104258
 0.13650225 0.34329376 0.56153564 0.26470736]


array([0.12989538, 0.13650225, 0.19516976, 0.26470736, 0.34329376,
       0.39765369, 0.56153564, 0.67104258, 0.74388177, 0.93482647])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [121]:
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))          #time taken using np.sum method

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))       #faster method

5.473852157592773
4.776954650878906


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [125]:
A=np.random.randint(10,size=(3,3))
B=np.random.randint(8,size=(3,3))
np.array_equal(A, B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [129]:
x = np.zeros(10)
x.flags.writeable = False          #x becomes read-only
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [130]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)                    #converted to polar coords
print(T)

[0.81032581 1.27663912 0.52343189 0.79924336 0.44412675 0.63691387
 0.68822247 1.04152201 1.0157736  0.88247237]
[0.74371009 0.89426728 0.38397957 0.1036317  0.03771283 1.24047529
 0.17760221 1.20547876 0.8104845  0.15650558]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [133]:
arr=np.random.random(10)
print(arr)
arr[(arr==arr.max())]=0           #replacing the max value by 0
arr

[0.15650355 0.50569678 0.81124153 0.67246287 0.41838941 0.73916464
 0.50202544 0.30312601 0.50053523 0.07700882]


array([0.15650355, 0.50569678, 0.        , 0.67246287, 0.41838941,
       0.73916464, 0.50202544, 0.30312601, 0.50053523, 0.07700882])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [135]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [141]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[-1.17255553e+05, -1.70728253e+06, -3.18177615e+04,
         5.28503960e+04,  3.32671209e+04],
       [ 2.67258327e+05, -9.36473043e+05, -1.70898006e+06,
         8.93079441e+05, -1.59996314e+05],
       [ 1.64296337e+05,  2.99682829e+06, -3.93353554e+05,
        -7.53500898e+05,  2.88345132e+06],
       [ 4.29791676e+06,  2.43833408e+04, -8.81825282e+03,
         2.97962737e+07, -1.80303976e+06],
       [ 3.39783377e+06, -2.76290251e+06,  1.32683087e+06,
         9.25364760e+07,  2.51129410e+06]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [154]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [148]:
arr=np.zeros(shape=(3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [152]:
arr=np.arange(23)
scalar=np.random.uniform(0,23)
print("scalar:",scalar)
index=(np.abs(arr-scalar)).argmin()
print(arr[index])

scalar: 6.987773707518942
7


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [153]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [6]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.22784252 0.20800671 0.52488122 0.56917192 0.4616962
  0.55908299 0.26944189 0.56996302 0.38482538]
 [0.22784252 0.         0.41573162 0.56030053 0.5427501  0.61483403
  0.58217455 0.37307068 0.39550786 0.48893329]
 [0.20800671 0.41573162 0.         0.45147882 0.54688923 0.28112692
  0.49219806 0.41074167 0.67893116 0.26954152]
 [0.52488122 0.56030053 0.45147882 0.         0.14972663 0.30832484
  0.04172413 0.7939653  0.50548284 0.1882959 ]
 [0.56917192 0.5427501  0.54688923 0.14972663 0.         0.45219659
  0.12331714 0.83499602 0.38745632 0.31157794]
 [0.4616962  0.61483403 0.28112692 0.30832484 0.45219659 0.
  0.34667726 0.6915257  0.73665182 0.16279149]
 [0.55908299 0.58217455 0.49219806 0.04172413 0.12331714 0.34667726
  0.         0.82849109 0.49749611 0.23000483]
 [0.26944189 0.37307068 0.41074167 0.7939653  0.83499602 0.6915257
  0.82849109 0.         0.76813177 0.64489618]
 [0.56996302 0.39550786 0.67893116 0.50548284 0.38745632 0.73665182
  0.49749611 0.7681317

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [7]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [8]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [9]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [10]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x**2+y**2)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [13]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*(4)), p, replace=False),1)
print(Z)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [15]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.27780712 -0.07805846 -0.2573426  -0.4589145   0.04720357 -0.09343157
  -0.26890779  0.31069644  0.07621466  0.44473314]
 [ 0.04250697  0.3122527   0.08075886 -0.17931693 -0.46886044  0.30445313
   0.24015949 -0.48014552  0.38011768 -0.23192593]
 [-0.35014501  0.36403819 -0.35586544 -0.13843754  0.2833154  -0.32404423
  -0.02716613  0.2498842  -0.03517382  0.33359438]
 [-0.15641584  0.23913036 -0.22622155 -0.29018712 -0.20585354 -0.12524726
   0.68757887 -0.00527801  0.36056376 -0.27806967]
 [-0.29598448 -0.07888131  0.21722233  0.33018295 -0.20975588 -0.07547223
   0.24277555  0.18073773 -0.22205618 -0.08876848]]


#### 59. How to sort an array by the nth column? (★★☆)

In [16]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 9 9]
 [0 6 0]
 [9 0 0]]
[[9 0 0]
 [0 6 0]
 [3 9 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [17]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [18]:
arr=np.arange(23)
scalar=np.random.uniform(0,23)
print("scalar:",scalar)
index=(np.abs(arr-scalar)).argmin()
print(arr[index])

scalar: 9.033240813174313
9


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)